"""add foreign key to onboarding

Revision ID: 739cba306079
Revises: eb71ba471d90
Create Date: 2025-12-29 12:50:39.500090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739cba306079'
down_revision = 'eb71ba471d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer()))
        batch_op.create_foreign_key(
            'fk_onboardings_employee_id',
            'employees',
            ['employee_id'],
            ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardings') as batch_op:
        batch_op.drop_constraint('fk_onboardings_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
