"""add foreign key to Review

Revision ID: eb71ba471d90
Revises: 4cd967b515ed
Create Date: 2025-12-29 12:48:25.046546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb71ba471d90'
down_revision = '4cd967b515ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_reviews_employee_id',
            'employees',
            ['employee_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
